name: Deploy Jekyll site to Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggers via webhook
  repository_dispatch:
    types:
    - webhook

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  METADATA_FILE_URL: https://docs.google.com/spreadsheets/d/e/2PACX-1vQ1w2oAELCjCt6BbEVv2UmRBOQ7OOXAZHHZLTwjlAQKUDKFHsGy4I9Eq1pp6a4lqTYrAvttEYjW75f_/pub?gid=0&single=true&output=csv

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build the site in the docker container
      run: |
        docker run --rm \
          -e METADATA_FILE_URL="${{ env.METADATA_FILE_URL }}" \
          -v ${{ github.workspace }}/app/_data:/app/_data \
          -v ${{ github.workspace }}/app/objects:/app/objects \
          -v ${{ github.workspace }}/app/pages:/app/pages \
          -v ${{ github.workspace }}/app/_config-github-pages.yml:/app/_config.yml \
          -v ${{ github.workspace }}/app/_includes/footer.html:/app/_includes/footer.html \
          -v ${{ github.workspace }}/app/_includes/item/citation-box.html:/app/_includes/item/citation-box.html \
          -v ${{ github.workspace }}/app/_includes/item/child/citation-box.html:/app/_includes/item/child/citation-box.html \
          -v ${{ github.workspace }}/app/_includes/item/rights-box.html:/app/_includes/item/rights-box.html \
          -v ${{ github.workspace }}/app/_layouts/home-infographic.html:/app/_layouts/home-infographic.html \
          -v ${{ github.workspace }}/_site:/app/_site \
          dhilsfu/collectionbuilder-docker rake deploy
    - name: Upload artifact
      # Automatically uploads an artifact from the './_site' directory by default
      uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
